-- Table: AVOID_MAN_CD
DROP TABLE AVOID_MAN_CD;
 CREATE TABLE AVOID_MAN_CD
(
id integer NOT NULL,
name character varying(38),
CONSTRAINT AVOID_MAN_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE AVOID_MAN_CD
OWNER TO postgres;
-- End Table

-- Table: BODY_TYPE
DROP TABLE BODY_TYPE;
 CREATE TABLE BODY_TYPE
(
id integer NOT NULL,
name character varying(58),
CONSTRAINT BODY_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE BODY_TYPE
OWNER TO postgres;
-- End Table

-- Table: CARGO_BD_TYPE
DROP TABLE CARGO_BD_TYPE;
 CREATE TABLE CARGO_BD_TYPE
(
id integer NOT NULL,
name character varying(16),
CONSTRAINT CARGO_BD_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE CARGO_BD_TYPE
OWNER TO postgres;
-- End Table

-- Table: CLOTHING_TYPE
DROP TABLE CLOTHING_TYPE;
 CREATE TABLE CLOTHING_TYPE
(
id integer NOT NULL,
name character varying(10),
CONSTRAINT CLOTHING_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE CLOTHING_TYPE
OWNER TO postgres;
-- End Table

-- Table: COLLISION_TYPE
DROP TABLE COLLISION_TYPE;
 CREATE TABLE COLLISION_TYPE
(
id integer NOT NULL,
name character varying(25),
CONSTRAINT COLLISION_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE COLLISION_TYPE
OWNER TO postgres;
-- End Table

-- Table: COUNTY
DROP TABLE COUNTY;
 CREATE TABLE COUNTY
(
id integer NOT NULL,
name character varying(14),
CONSTRAINT COUNTYid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE COUNTY
OWNER TO postgres;
-- End Table

-- Table: DAMAGE_IND
DROP TABLE DAMAGE_IND;
 CREATE TABLE DAMAGE_IND
(
id integer NOT NULL,
name character varying(35),
CONSTRAINT DAMAGE_INDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DAMAGE_IND
OWNER TO postgres;
-- End Table

-- Table: DAY_OF_WEEK
DROP TABLE DAY_OF_WEEK;
 CREATE TABLE DAY_OF_WEEK
(
id integer NOT NULL,
name character varying(9),
CONSTRAINT DAY_OF_WEEKid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DAY_OF_WEEK
OWNER TO postgres;
-- End Table

-- Table: DISTRICT
DROP TABLE DISTRICT;
 CREATE TABLE DISTRICT
(
id integer NOT NULL,
name character varying(107),
CONSTRAINT DISTRICTid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DISTRICT
OWNER TO postgres;
-- End Table

-- Table: DVR_PED_CONDITION
DROP TABLE DVR_PED_CONDITION;
 CREATE TABLE DVR_PED_CONDITION
(
id integer NOT NULL,
name character varying(17),
CONSTRAINT DVR_PED_CONDITIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE DVR_PED_CONDITION
OWNER TO postgres;
-- End Table

-- Table: EJECTION_IND
DROP TABLE EJECTION_IND;
 CREATE TABLE EJECTION_IND
(
id integer NOT NULL,
name character varying(17),
CONSTRAINT EJECTION_INDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE EJECTION_IND
OWNER TO postgres;
-- End Table

-- Table: EJECT_PATH_CD
DROP TABLE EJECT_PATH_CD;
 CREATE TABLE EJECT_PATH_CD
(
id integer NOT NULL,
name character varying(44),
CONSTRAINT EJECT_PATH_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE EJECT_PATH_CD
OWNER TO postgres;
-- End Table

-- Table: EXTRIC_IND
DROP TABLE EXTRIC_IND;
 CREATE TABLE EXTRIC_IND
(
id integer NOT NULL,
name character varying(30),
CONSTRAINT EXTRIC_INDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE EXTRIC_IND
OWNER TO postgres;
-- End Table

-- Table: GRADE
DROP TABLE GRADE;
 CREATE TABLE GRADE
(
id integer NOT NULL,
name character varying(21),
CONSTRAINT GRADEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE GRADE
OWNER TO postgres;
-- End Table

-- Table: HAZMAT_CODE
DROP TABLE HAZMAT_CODE;
 CREATE TABLE HAZMAT_CODE
(
id character varying(1) NOT NULL,
name character varying(45),
CONSTRAINT HAZMAT_CODEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE HAZMAT_CODE
OWNER TO postgres;
-- End Table

-- Table: ILLUMINATION
DROP TABLE ILLUMINATION;
 CREATE TABLE ILLUMINATION
(
id integer NOT NULL,
name character varying(28),
CONSTRAINT ILLUMINATIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE ILLUMINATION
OWNER TO postgres;
-- End Table

-- Table: INJ_SEVERITY
DROP TABLE INJ_SEVERITY;
 CREATE TABLE INJ_SEVERITY
(
id integer NOT NULL,
name character varying(24),
CONSTRAINT INJ_SEVERITYid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE INJ_SEVERITY
OWNER TO postgres;
-- End Table

-- Table: INTERSECT_TYPE
DROP TABLE INTERSECT_TYPE;
 CREATE TABLE INTERSECT_TYPE
(
id integer NOT NULL,
name character varying(29),
CONSTRAINT INTERSECT_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE INTERSECT_TYPE
OWNER TO postgres;
-- End Table

-- Table: IMPACT_POINT
DROP TABLE IMPACT_POINT;
 CREATE TABLE IMPACT_POINT
(
id integer NOT NULL,
name character varying(19),
CONSTRAINT IMPACT_POINTid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE IMPACT_POINT
OWNER TO postgres;
-- End Table

-- Table: LANE_CLOSURE_DIRECTION
DROP TABLE LANE_CLOSURE_DIRECTION;
 CREATE TABLE LANE_CLOSURE_DIRECTION
(
id integer NOT NULL,
name character varying(15),
CONSTRAINT LANE_CLOSURE_DIRECTIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE LANE_CLOSURE_DIRECTION
OWNER TO postgres;
-- End Table

-- Table: LOCATION_TYPE
DROP TABLE LOCATION_TYPE;
 CREATE TABLE LOCATION_TYPE
(
id integer NOT NULL,
name character varying(23),
CONSTRAINT LOCATION_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE LOCATION_TYPE
OWNER TO postgres;
-- End Table

-- Table: MAKE_CD
DROP TABLE MAKE_CD;
 CREATE TABLE MAKE_CD
(
id integer NOT NULL,
name character varying(23),
CONSTRAINT MAKE_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MAKE_CD
OWNER TO postgres;
-- End Table

-- Table: MC_DVR_HLMT_TYPE
DROP TABLE MC_DVR_HLMT_TYPE;
 CREATE TABLE MC_DVR_HLMT_TYPE
(
id integer NOT NULL,
name character varying(17),
CONSTRAINT MC_DVR_HLMT_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MC_DVR_HLMT_TYPE
OWNER TO postgres;
-- End Table

-- Table: MC_PAS_HLMT_TYPE
DROP TABLE MC_PAS_HLMT_TYPE;
 CREATE TABLE MC_PAS_HLMT_TYPE
(
id integer NOT NULL,
name character varying(17),
CONSTRAINT MC_PAS_HLMT_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MC_PAS_HLMT_TYPE
OWNER TO postgres;
-- End Table

-- Table: OWNER_DRIVER
DROP TABLE OWNER_DRIVER;
 CREATE TABLE OWNER_DRIVER
(
id integer NOT NULL,
name character varying(45),
CONSTRAINT OWNER_DRIVERid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE OWNER_DRIVER
OWNER TO postgres;
-- End Table

-- Table: PED_LOCATION
DROP TABLE PED_LOCATION;
 CREATE TABLE PED_LOCATION
(
id integer NOT NULL,
name character varying(33),
CONSTRAINT PED_LOCATIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PED_LOCATION
OWNER TO postgres;
-- End Table

-- Table: PED_SIGNAL
DROP TABLE PED_SIGNAL;
 CREATE TABLE PED_SIGNAL
(
id integer NOT NULL,
name character varying(20),
CONSTRAINT PED_SIGNALid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PED_SIGNAL
OWNER TO postgres;
-- End Table

-- Table: PERSON_TYPE
DROP TABLE PERSON_TYPE;
 CREATE TABLE PERSON_TYPE
(
id integer NOT NULL,
name character varying(10),
CONSTRAINT PERSON_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE PERSON_TYPE
OWNER TO postgres;
-- End Table

-- Table: RELATION_TO_ROAD
DROP TABLE RELATION_TO_ROAD;
 CREATE TABLE RELATION_TO_ROAD
(
id integer NOT NULL,
name character varying(51),
CONSTRAINT RELATION_TO_ROADid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RELATION_TO_ROAD
OWNER TO postgres;
-- End Table

-- Table: RESTRAINT_HELMET
DROP TABLE RESTRAINT_HELMET;
 CREATE TABLE RESTRAINT_HELMET
(
id integer NOT NULL,
name character varying(33),
CONSTRAINT RESTRAINT_HELMETid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RESTRAINT_HELMET
OWNER TO postgres;
-- End Table

-- Table: ROAD_CONDITION
DROP TABLE ROAD_CONDITION;
 CREATE TABLE ROAD_CONDITION
(
id integer NOT NULL,
name character varying(31),
CONSTRAINT ROAD_CONDITIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE ROAD_CONDITION
OWNER TO postgres;
-- End Table

-- Table: ROAD_OWNER
DROP TABLE ROAD_OWNER;
 CREATE TABLE ROAD_OWNER
(
id integer NOT NULL,
name character varying(29),
CONSTRAINT ROAD_OWNERid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE ROAD_OWNER
OWNER TO postgres;
-- End Table

-- Table: RDWY_ALIGNMENT
DROP TABLE RDWY_ALIGNMENT;
 CREATE TABLE RDWY_ALIGNMENT
(
id integer NOT NULL,
name character varying(8),
CONSTRAINT RDWY_ALIGNMENTid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RDWY_ALIGNMENT
OWNER TO postgres;
-- End Table

-- Table: RDWY_ORIENT
DROP TABLE RDWY_ORIENT;
 CREATE TABLE RDWY_ORIENT
(
id character varying(1) NOT NULL,
name character varying(7),
CONSTRAINT RDWY_ORIENTid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE RDWY_ORIENT
OWNER TO postgres;
-- End Table

-- Table: SEAT_POSITION
DROP TABLE SEAT_POSITION;
 CREATE TABLE SEAT_POSITION
(
id integer NOT NULL,
name character varying(43),
CONSTRAINT SEAT_POSITIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SEAT_POSITION
OWNER TO postgres;
-- End Table

-- Table: SEX
DROP TABLE SEX;
 CREATE TABLE SEX
(
id character varying(1) NOT NULL,
name character varying(7),
CONSTRAINT SEXid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SEX
OWNER TO postgres;
-- End Table

-- Table: SPECIAL_USAGE
DROP TABLE SPECIAL_USAGE;
 CREATE TABLE SPECIAL_USAGE
(
id integer NOT NULL,
name character varying(23),
CONSTRAINT SPECIAL_USAGEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SPECIAL_USAGE
OWNER TO postgres;
-- End Table

-- Table: SPEC_JURIS_CD
DROP TABLE SPEC_JURIS_CD;
 CREATE TABLE SPEC_JURIS_CD
(
id integer NOT NULL,
name character varying(25),
CONSTRAINT SPEC_JURIS_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SPEC_JURIS_CD
OWNER TO postgres;
-- End Table

-- Table: SURFACE_TYPE
DROP TABLE SURFACE_TYPE;
 CREATE TABLE SURFACE_TYPE
(
id integer NOT NULL,
name character varying(22),
CONSTRAINT SURFACE_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE SURFACE_TYPE
OWNER TO postgres;
-- End Table

-- Table: TCD_FUNC_CD
DROP TABLE TCD_FUNC_CD;
 CREATE TABLE TCD_FUNC_CD
(
id integer NOT NULL,
name character varying(29),
CONSTRAINT TCD_FUNC_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE TCD_FUNC_CD
OWNER TO postgres;
-- End Table

-- Table: TCD_TYPE
DROP TABLE TCD_TYPE;
 CREATE TABLE TCD_TYPE
(
id integer NOT NULL,
name character varying(28),
CONSTRAINT TCD_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE TCD_TYPE
OWNER TO postgres;
-- End Table

-- Table: TRAVEL_DIRECTION
DROP TABLE TRAVEL_DIRECTION;
 CREATE TABLE TRAVEL_DIRECTION
(
id character varying(1) NOT NULL,
name character varying(7),
CONSTRAINT TRAVEL_DIRECTIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE TRAVEL_DIRECTION
OWNER TO postgres;
-- End Table

-- Table: TRL_VEH_TYPE_CD
DROP TABLE TRL_VEH_TYPE_CD;
 CREATE TABLE TRL_VEH_TYPE_CD
(
id integer NOT NULL,
name character varying(22),
CONSTRAINT TRL_VEH_TYPE_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE TRL_VEH_TYPE_CD
OWNER TO postgres;
-- End Table

-- Table: UNDER_RIDE_IND
DROP TABLE UNDER_RIDE_IND;
 CREATE TABLE UNDER_RIDE_IND
(
id integer NOT NULL,
name character varying(41),
CONSTRAINT UNDER_RIDE_INDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE UNDER_RIDE_IND
OWNER TO postgres;
-- End Table

-- Table: UNIT_TYPE
DROP TABLE UNIT_TYPE;
 CREATE TABLE UNIT_TYPE
(
id integer NOT NULL,
name character varying(38),
CONSTRAINT UNIT_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE UNIT_TYPE
OWNER TO postgres;
-- End Table

-- Table: URBAN_RURAL
DROP TABLE URBAN_RURAL;
 CREATE TABLE URBAN_RURAL
(
id integer NOT NULL,
name character varying(39),
CONSTRAINT URBAN_RURALid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE URBAN_RURAL
OWNER TO postgres;
-- End Table

-- Table: VEH_TYPE
DROP TABLE VEH_TYPE;
 CREATE TABLE VEH_TYPE
(
id integer NOT NULL,
name character varying(29),
CONSTRAINT VEH_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VEH_TYPE
OWNER TO postgres;
-- End Table

-- Table: VEH_POSITION
DROP TABLE VEH_POSITION;
 CREATE TABLE VEH_POSITION
(
id integer NOT NULL,
name character varying(30),
CONSTRAINT VEH_POSITIONid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VEH_POSITION
OWNER TO postgres;
-- End Table

-- Table: VEH_CONFIG_CD
DROP TABLE VEH_CONFIG_CD;
 CREATE TABLE VEH_CONFIG_CD
(
id integer NOT NULL,
name character varying(53),
CONSTRAINT VEH_CONFIG_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VEH_CONFIG_CD
OWNER TO postgres;
-- End Table

-- Table: VEH_COLOR_CD
DROP TABLE VEH_COLOR_CD;
 CREATE TABLE VEH_COLOR_CD
(
id integer NOT NULL,
name character varying(7),
CONSTRAINT VEH_COLOR_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VEH_COLOR_CD
OWNER TO postgres;
-- End Table

-- Table: VEH_MOVEMENT
DROP TABLE VEH_MOVEMENT;
 CREATE TABLE VEH_MOVEMENT
(
id integer NOT NULL,
name character varying(44),
CONSTRAINT VEH_MOVEMENTid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VEH_MOVEMENT
OWNER TO postgres;
-- End Table

-- Table: VINA_BODY_TYPE_CD
DROP TABLE VINA_BODY_TYPE_CD;
 CREATE TABLE VINA_BODY_TYPE_CD
(
id character varying(3) NOT NULL,
name character varying(46),
CONSTRAINT VINA_BODY_TYPE_CDid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE VINA_BODY_TYPE_CD
OWNER TO postgres;
-- End Table

-- Table: WEATHER
DROP TABLE WEATHER;
 CREATE TABLE WEATHER
(
id integer NOT NULL,
name character varying(21),
CONSTRAINT WEATHERid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE WEATHER
OWNER TO postgres;
-- End Table

-- Table: WORK_ZONE_LOC
DROP TABLE WORK_ZONE_LOC;
 CREATE TABLE WORK_ZONE_LOC
(
id integer NOT NULL,
name character varying(37),
CONSTRAINT WORK_ZONE_LOCid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE WORK_ZONE_LOC
OWNER TO postgres;
-- End Table

-- Table: WORK_ZONE_TYPE
DROP TABLE WORK_ZONE_TYPE;
 CREATE TABLE WORK_ZONE_TYPE
(
id integer NOT NULL,
name character varying(15),
CONSTRAINT WORK_ZONE_TYPEid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE WORK_ZONE_TYPE
OWNER TO postgres;
-- End Table

-- Table: STATE_CODES
DROP TABLE STATE_CODES;
 CREATE TABLE STATE_CODES
(
id character varying(2) NOT NULL,
name character varying(23),
CONSTRAINT STATE_CODESid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE STATE_CODES
OWNER TO postgres;
-- End Table

-- Table: MUNICIPALITIES
DROP TABLE MUNICIPALITIES;
 CREATE TABLE MUNICIPALITIES
(
id integer NOT NULL,
name character varying(32),
CONSTRAINT MUNICIPALITIESid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE MUNICIPALITIES
OWNER TO postgres;
-- End Table

-- Table: POLICE_AGENCIES
DROP TABLE POLICE_AGENCIES;
 CREATE TABLE POLICE_AGENCIES
(
id character varying(5) NOT NULL,
name character varying(37),
CONSTRAINT POLICE_AGENCIESid PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE POLICE_AGENCIES
OWNER TO postgres;
-- End Table

